name: example
description: An example for ext_theme.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ext_theme: 0.0.1-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

  ext_theme_generator: 0.0.1-dev.2

# uncomment when working locally
dependency_overrides:
  ext_theme_generator:
    path: ../ext_theme_generator
  ext_theme:
    path: ../ext_theme

flutter:
  uses-material-design: true