name: ext_theme
description: >- 
  Easily extend the theming in Flutter with your custom properties.
  To be used with 'ext_theme_generator'.
version: 0.0.1-dev.2
homepage: 
repository: https://github.com/SEGVeenstra/ext_theme
issue_tracker: https://github.com/SEGVeenstra/ext_theme/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
