builders:
  extendedThemeBuilder:
    import: 'package:extended_theme_generator/generator.dart'
    builder_factories: [extendedThemeBuilder]
    auto_apply: dependents
    build_extensions: {".dart": [".theme.part"]}
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]