builders:
  extThemeBuilder:
    import: 'package:ext_theme_generator/generator.dart'
    builder_factories: [extThemeBuilder]
    auto_apply: dependents
    build_extensions: {".dart": [".theme.g.part"]}
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]