name: ext_theme_generator
description: Generator for ext_theme.
version: 0.0.1-dev.2
homepage: 
repository: https://github.com/SEGVeenstra/ext_theme
issue_tracker: https://github.com/SEGVeenstra/ext_theme/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  build: ^2.2.1
  source_gen: ^1.2.1
  ext_theme: ^0.0.1-dev.2
  analyzer: ^3.1.0

# Uncomment when working locally
# dependency_overrides:
#   ext_theme:
#     path: ../ext_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  

flutter:

