name: ext_theme_generator
description: Generator for ext_theme.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  build: ^2.2.1
  source_gen: ^1.2.1
  ext_theme:
    git:
      url: git@github.com:SEGVeenstra/ext_theme.git
      path: ext_theme

dependency_overrides:
  ext_theme:
    path: ../ext_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  

flutter:

